CREATE TABLE IF NOT EXISTS `site_app_manager` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `APP_ID` int(11) DEFAULT NULL COMMENT '站点编号',
  `MANAGER_ID` varchar(255) DEFAULT NULL COMMENT '管理员编号',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='管理员站点关联表';
