CREATE TABLE IF NOT EXISTS `statistics_sql` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `SS_SQL` varchar(4000) DEFAULT NULL COMMENT '统计SQL',
  `SS_TYPE` varchar(255) DEFAULT NULL COMMENT '统计类型',
  `SS_KEY` varchar(255) DEFAULT NULL COMMENT '统计KEY值',
  `SS_NAME` varchar(255) DEFAULT NULL COMMENT '统计名称',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(11) DEFAULT NULL COMMENT '修改人',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(11) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=90 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='统计';
CREATE TABLE IF NOT EXISTS `access_statistics` (
  `id` bigint(19) unsigned NOT NULL AUTO_INCREMENT,
  `IP` varchar(255) DEFAULT NULL COMMENT '用户ip',
  `URL` varchar(255) DEFAULT NULL COMMENT '访问链接',
  `DEVICE_TYPE` varchar(255) DEFAULT NULL COMMENT '设备类型',
  `USER_AGENT` text COMMENT '浏览器标识',
  `ACCESS_TIME` varchar(255) DEFAULT NULL COMMENT '浏览时长',
  `END_VIEW_TIME` datetime DEFAULT NULL COMMENT '结束浏览时间',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '地理位置',
  `COOKIE` varchar(255) DEFAULT NULL COMMENT '访客',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=314 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='访问统计';
