CREATE TABLE IF NOT EXISTS `id_rule` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `IR_TYPE` varchar(255) DEFAULT NULL COMMENT '类型',
  `IR_NAME` varchar(255) DEFAULT NULL COMMENT '规则名称',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(11) DEFAULT NULL COMMENT '修改人',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(11) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='规则';
CREATE TABLE IF NOT EXISTS `id_rule_data` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `IRD_OPTION` varchar(255) DEFAULT NULL COMMENT '选项',
  `IRD_TYPE` varchar(255) DEFAULT NULL COMMENT '组成类型',
  `IR_ID` int(11) DEFAULT NULL COMMENT '关联ID',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(11) DEFAULT NULL COMMENT '修改人',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(11) DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 COMMENT='规则数据';
