server:
  port: 8080
  servlet: 
    context-path: /
  
spring:
  datasource:
    url: jdbc:mysql://sh-cdb-hi3odex2.sql.tencentcdb.com:59481/mcms-gov?useUnicode=true&characterEncoding=utf8
    username: root
    password: rMU4m8Mv73pTEmNt
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1

#数据权限配置
pagehelper:
  helper-dialect: net.mingsoft.datascope.dialect.MySqlPermissionDialect

mybatis-plus:
  #因为IBaseDao是一个抽象类，没有实体，所以自动注入的时候不会注入，需要手动映射
  mapper-locations: classpath*:/net/mingsoft/base/dao/IBaseDao.xml
  global-config:
    db-config:
      id-type: auto
      where-strategy: not_empty #防止空串及null拼接条件
  configuration:
    database-id: mysql
    #设置当查询结果值为null时，同样映射该查询字段给map。
    call-setters-on-nulls: true