server:
  port: 8080 # 生产时建议更改为80
  servlet.session.timeout: P0DT60M0S #D天H小时M分钟S秒，字符T是紧跟在时分秒之前的，每个单位都必须由数字开始,且时分秒顺序不能乱
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
#  ssl: #https证书配置 配置了之后只能通过https访问应用
#    key-store: ms.pfx 证书文件
#    key-store-password: 3MU9t9Cz 证书密码


#配置日志
logging:
  level:
    net.mingsoft: debug
    net.mingsoft.base.dao.IBaseDao: debug
    org.springframework.boot.autoconfigure: error
    org.springframework.web: error
  config: classpath:log4j-spring.xml

ms:
  #shiro-key: #16位长度，不填写默认随机生成
  cookie-name: GOV_SHIRO_SESSION_ID
  #scheme: https #解决使用代理服务器代理应用时标签解析域名依旧为http的问题
  swagger:
    enable: true #启用swagger文档，生产的时候务必关掉 访问地址：http://ip|域名/项目发布名/swagger-ui.html
  manager:
    login-path: /login.do
    path: /ms #后台访问的路径，如:http://项目/ms/login.do，生产的时候建议修改
  people:
    login-url: /mdiyPage/out/login.do
  upload:
    path: upload #文件上传路径，可以根据实际写绝对路径
    denied: .exe,.jsp
  html-dir: html #所有静态文件生成总目录

spring:
  main:
    allow-circular-references: true
  elasticsearch:
    uris: [127.0.0.1:9200]
  data:
    elasticsearch:
      repositories:
        enabled: false

  cache:
    type: ehcache
  datasource:
    druid:
      initialSize: 5 #初始连接数，默认0
      minIdle: 5  #最小连接数，默认8
      maxActive: 20 #最大连接数，默认8
      maxWait: 6000 #获取连接的最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒,去掉可能会造成登录卡主问题
      testOnBorrow: true #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      poolPreparedStatements: true #可以支持PSCache（提升写入、查询效率）
      keepAlive: true #保持长连接
      stat-view-servlet:
        enabled: false #启用druid监控 地址druid/sql.html


  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**
  servlet:
    multipart:
      max-request-size: 100MB
      enabled: false
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    allow-request-override: true
    allow-session-override: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: false
    template-loader-path: file:WEB-INF/,file:WEB-INF/manager,classpath:/,classpath:/WEB-INF/manager,classpath:/WEB-INF
    settings:
      template_update_delay: 1
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #2.6版本Spring MVC 处理映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser
      use-suffix-pattern: true
