CREATE TABLE IF NOT EXISTS `wx_article` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '文章id',
  `draft_id` varchar(21) DEFAULT NULL COMMENT '微信草稿编号',
  `content_id` varchar(50) DEFAULT NULL COMMENT 'mcms的文章内容id',
  `article_thumbnails` varchar(4000) DEFAULT NULL COMMENT '文章图片',
  `article_sort` int(11) DEFAULT NULL COMMENT '文章排序',
  `article_hit` int(11) DEFAULT NULL COMMENT '文章点击数',
  `article_display` varchar(11) DEFAULT NULL COMMENT '是否显示',
  `article_content` text COMMENT '文章内容',
  `article_type` varchar(255) DEFAULT NULL COMMENT '素材类型',
  `article_url` varchar(255) DEFAULT NULL COMMENT '原文链接',
  `article_source` varchar(255) DEFAULT NULL COMMENT '文章来源',
  `article_description` varchar(255) DEFAULT NULL COMMENT '文章描述',
  `article_author` varchar(255) DEFAULT NULL COMMENT '文章作者',
  `article_title` varchar(255) DEFAULT NULL COMMENT '文章标题',
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `update_by` int(11) DEFAULT NULL COMMENT '修改人',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `del` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='文章';
CREATE TABLE IF NOT EXISTS `wx_category` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '分类id',
  `weixin_id` int(11) NOT NULL COMMENT '微信编号',
  `category_img` varchar(4000) DEFAULT NULL COMMENT '分类略缩图',
  `category_description` varchar(255) DEFAULT NULL COMMENT '分类描述',
  `category_id` int(11) DEFAULT NULL COMMENT '父类别编号',
  `category_title` varchar(255) DEFAULT NULL COMMENT '类别标题',
  `update_date` datetime DEFAULT NULL COMMENT '修改时间',
  `update_by` int(11) DEFAULT NULL COMMENT '修改人',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` int(11) DEFAULT NULL COMMENT '创建人',
  `del` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='分类';
CREATE TABLE IF NOT EXISTS `wx_draft` (
  `ID` bigint(19) NOT NULL,
  `WEIXIN_ID` int(11) DEFAULT NULL COMMENT '微信ID',
  `MASTER_ARTICLE_ID` int(11) DEFAULT NULL COMMENT '主图文ID',
  `CHILD_ARTICLE_IDS` varchar(255) DEFAULT NULL COMMENT '子图文IDS',
  `MEDIA_ID` varchar(255) DEFAULT NULL COMMENT '微信媒体ID',
  `PUBLISH_ID` varchar(255) DEFAULT NULL COMMENT '发布ID',
  `PUBLISH_STATE` int(1) DEFAULT '0' COMMENT '发布状态 0:未发布,1:发布中,2:发布成功,3:发布失败',
  `ARTICLE_ID` varchar(255) DEFAULT NULL COMMENT '已发布草稿的ID',
  `DRAFT_URL` varchar(255) DEFAULT NULL COMMENT '已发表的链接地址',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='草稿';
CREATE TABLE IF NOT EXISTS `wx_file` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '文件编号',
  `category_id` int(11) DEFAULT NULL COMMENT '文件分类编号',
  `file_name` varchar(200) DEFAULT NULL COMMENT '文件名称',
  `file_url` varchar(500) DEFAULT NULL COMMENT '文件链接',
  `file_size` int(11) DEFAULT NULL COMMENT '文件大小',
  `file_json` varchar(500) DEFAULT NULL COMMENT '文件详情Json数据',
  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型：图片、音频、视频等',
  `is_child` varchar(50) DEFAULT NULL COMMENT '子业务',
  `weixin_id` int(11) DEFAULT NULL COMMENT '微信编号',
  `file_media_id` varchar(300) DEFAULT NULL COMMENT '微信接口反馈参数',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `update_by` int(11) DEFAULT NULL COMMENT '更新者',
  `create_by` int(11) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `del` int(1) DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=684 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='微信素材文件';
CREATE TABLE IF NOT EXISTS `wx_weixin` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id主键',
  `WEIXIN_NO` varchar(30) DEFAULT NULL COMMENT '信号号',
  `WEIXIN_ORIGIN_ID` varchar(30) DEFAULT NULL COMMENT '微信原始ID',
  `WEIXIN_NAME` varchar(30) NOT NULL COMMENT '众号公名称',
  `WEIXIN_TYPE` int(1) NOT NULL DEFAULT '0' COMMENT '信微号类型 0：服务号 1：订阅号',
  `WEIXIN_TOKEN` varchar(30) DEFAULT NULL COMMENT '信微token',
  `WEIXIN_IMAGE` varchar(100) DEFAULT NULL COMMENT '信微二维码图片',
  `WEIXIN_APPID` varchar(150) NOT NULL COMMENT '微信公众号APPID',
  `WEIXIN_APPSECRET` varchar(150) NOT NULL COMMENT '用应授权码',
  `WEIXIN_HEADIMG` varchar(150) DEFAULT NULL COMMENT '信微帐号头像',
  `WEIXIN_MCHID` varchar(255) DEFAULT NULL COMMENT '微信支付商户号',
  `WEIXIN_PAYKEY` varchar(255) DEFAULT NULL COMMENT '支付key',
  `WEIXIN_RROXY_URL` varchar(500) DEFAULT NULL COMMENT '微信内网测试地址',
  `WEIXIN_OAUTH_URL` varchar(200) DEFAULT NULL COMMENT '网页2.0授权地址,需要加http',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='微信公众帐号';
CREATE TABLE IF NOT EXISTS `wx_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id主键',
  `MENU_TITLE` varchar(20) DEFAULT NULL COMMENT '单菜名称',
  `MENU_URL` varchar(300) DEFAULT NULL COMMENT '单菜链接地址',
  `MENU_STATUS` int(1) DEFAULT NULL COMMENT '菜单状态 0：不启用 1：启用',
  `MENU_MENU_ID` int(22) DEFAULT NULL COMMENT '父菜单编号',
  `MENU_TYPE` int(2) DEFAULT NULL COMMENT '菜单属性 0:链接 1:回复',
  `MENU_SORT` int(11) DEFAULT NULL COMMENT '菜单排序',
  `MENU_STYLE` varchar(20) DEFAULT 'text' COMMENT '类型：imageText单图文 text文本 image图片 moreImageText多图文 link链接 voice语音 video视频',
  `MENU_OAUTH_ID` int(11) NOT NULL DEFAULT '0' COMMENT '授权数据编号',
  `MENU_WEIXIN_ID` int(11) DEFAULT NULL COMMENT '微信编号',
  `MENU_CONTENT` varchar(255) DEFAULT NULL COMMENT '菜单内容',
  `MENU_PAGEPATH` varchar(255) DEFAULT NULL COMMENT '小程序路径',
  `MINIPROGRAM_APPID` varchar(255) DEFAULT NULL COMMENT '小程序AppId',
  PRIMARY KEY (`id`,`MENU_OAUTH_ID`) USING BTREE,
  KEY `fk_menu_weixin_id` (`MENU_WEIXIN_ID`) USING BTREE,
  CONSTRAINT `wx_menu_ibfk_1` FOREIGN KEY (`MENU_WEIXIN_ID`) REFERENCES `wx_weixin` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='微信菜单';
CREATE TABLE IF NOT EXISTS `wx_passive_message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `PM_WEIXIN_ID` int(11) NOT NULL COMMENT '微信编号',
  `PM_EVENT_ID` int(22) NOT NULL DEFAULT '0' COMMENT '该回复属于的分类中的事件ID,1新关注2二维码扫描5未关注扫描二维码6点击事件4文本消息3二维码扫描&提示框',
  `PM_NEWS_ID` int(22) DEFAULT '0' COMMENT '回复的素材ID',
  `PM_MESSAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT '对应自定义模板回复消息id,与PM_NEWS_ID只能同时存在一个',
  `PM_APP_ID` int(22) NOT NULL DEFAULT '0' COMMENT '该回复所属的应用ID',
  `PM_REPLY_NUM` int(22) DEFAULT '0' COMMENT '被动回复的次数;为1时表示用户第一次被动响应消息,依次递增,当超出时取值为0的进行回复',
  `PM_KEY` varchar(300) DEFAULT NULL COMMENT '事件关键字',
  `PM_TYPE` varchar(20) NOT NULL DEFAULT 'keyword' COMMENT '回复属性:keyword,关键字回复，attention,关注回复，passivity,被动回复,all,群发',
  `PM_TAG` varchar(30) DEFAULT NULL COMMENT '回复目标',
  `PM_CONTENT` varchar(255) NOT NULL COMMENT '消息回复内容',
  `PM_NEW_TYPE` varchar(20) DEFAULT 'text' COMMENT '素材类型 text 回复文本消息、image 回复图片消息、imageText 回复图文消息、voice 回复语音消息、video 回复视频消息',
  `UPDATE_BY` varchar(30) DEFAULT NULL COMMENT '更新人员ID',
  `CREATE_BY` varchar(30) DEFAULT NULL COMMENT '创建人员ID',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '更新时间',
  `DEL` int(1) DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `fk_pm_message_id` (`PM_WEIXIN_ID`) USING BTREE,
  CONSTRAINT `wx_passive_message_ibfk_1` FOREIGN KEY (`PM_WEIXIN_ID`) REFERENCES `wx_weixin` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='微信被动消息回复';
CREATE TABLE IF NOT EXISTS `wx_template` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `WEIXIN_ID` varchar(255) DEFAULT NULL COMMENT '微信编号',
  `TEMPLATE_ID` varchar(255) DEFAULT NULL COMMENT '模板编号',
  `TEMPLATE_TITLE` varchar(255) DEFAULT NULL COMMENT '模板名称',
  `TEMPLATE_CODE` varchar(255) DEFAULT NULL COMMENT '模版编码',
  `TEMPLATE_PRIMARY_INDUSTRY` varchar(255) DEFAULT NULL COMMENT '主属行业',
  `TEMPLATE_DEPUTY_INDUSTRY` varchar(255) DEFAULT NULL COMMENT '副属行业',
  `TEMPLATE_CONTENT` varchar(255) DEFAULT NULL COMMENT '内容',
  `TEMPLATE_EXAMPLE` varchar(255) DEFAULT NULL COMMENT '样例',
  `TEMPLATE_KEYWORD` varchar(255) DEFAULT NULL COMMENT '模板关键词',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1673931644348215299 DEFAULT CHARSET=utf8 COMMENT='微信消息模板';
CREATE TABLE IF NOT EXISTS `wx_qr_log` (
  `id` bigint(11) unsigned NOT NULL,
  `OPEN_ID` varchar(255) DEFAULT NULL COMMENT '会员微信唯一编号',
  `WEIXIN_ID` varchar(255) DEFAULT NULL COMMENT '微信编号',
  `QC_ID` varchar(255) DEFAULT NULL COMMENT '场景二维码编号',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='场景二维码日志';
CREATE TABLE IF NOT EXISTS `wx_qr_code` (
  `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT,
  `WEIXIN_ID` varchar(255) DEFAULT NULL COMMENT '微信编号',
  `QC_SCENE_STR` varchar(255) DEFAULT NULL COMMENT '场景值id(名称)',
  `QC_ACTION_NAME` varchar(255) DEFAULT NULL COMMENT '二维码类型',
  `QC_EXPIRE_SECONDS` bigint(19) DEFAULT NULL COMMENT '二维码有效期',
  `QC_BEAN_NAME` varchar(255) DEFAULT NULL COMMENT '实现类bean名称',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATE_BY` varchar(50) DEFAULT NULL COMMENT '创建人',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  `UPDATE_BY` varchar(50) DEFAULT NULL COMMENT '修改人',
  `DEL` int(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1667381000984408067 DEFAULT CHARSET=utf8 COMMENT='场景二维码管理';
CREATE TABLE IF NOT EXISTS `wx_people` (
  `WEIXIN_ID` int(11) DEFAULT NULL COMMENT '微信编号',
  `PEOPLE_ID` int(11) DEFAULT NULL COMMENT '关联用户基本信息ID',
  `OPEN_ID` varchar(100) DEFAULT NULL COMMENT '户用在微信中的唯一标识',
  `SUBSCRIBE` int(2) DEFAULT NULL COMMENT '关注状态,0为未关注',
  `HEADIMG_URL` varchar(500) DEFAULT NULL COMMENT '户用头像链接地址',
  `SUBSCRIBE_TIME` timestamp NULL DEFAULT NULL COMMENT '用户关注时间',
  `SUBSCRIBE_SCENE` varchar(255) DEFAULT NULL COMMENT '用户关注的渠道来源'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='微信用户表';
